name: example
description: Example project for aug_validateform.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  aug_validateform:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  aug_validateform_generator:
    path: ../../aug_validateform_generator
  build_runner: ^2.4.8
  analyzer: ^6.4.1


dependency_overrides:
  aug_validateform:
    path: ../
  aug_validateform_annotations:
    path: ../../aug_validateform_annotations

flutter:
  uses-material-design: true
