name: aug_validateform_generator
description: Code generator for aug_validateform using Dart Augmentations.
version: 0.0.1
environment:
  sdk: '>=3.6.0-0 <4.0.0'

dependencies:
  aug_validateform:
    path: ../aug_validateform
  analyzer: '>=6.4.0 <10.0.0'
  build: ^2.4.1
  source_gen: ^1.5.0
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.8
  build_test: ^2.2.0
  test: ^1.25.0
  lints: ^3.0.0
