name: aug_validateform_generator
description: High-performance code generator for aug_validateform. Automates reactive validation logic using Dart Augmentations for boilerplate-free Flutter forms.
version: 0.0.1-dev.7
environment:
  sdk: '>=3.6.0-0 <4.0.0'

homepage: https://github.com/umarKhan1/aug_validateform
repository: https://github.com/umarKhan1/aug_validateform/tree/main/packages/aug_validateform_generator

dependencies:
  aug_validateform_annotations: ^0.0.1-dev.1
  analyzer: ^9.0.0
  build: ^4.0.3
  source_gen: ^4.1.1
  code_builder: ^4.11.0
  dart_style: ^3.1.3
  path: ^1.9.1


dev_dependencies:
  build_runner: ^2.10.4
  build_test: ^3.5.4
  test: ^1.28.0
  lints: ^6.0.0
