name: aug_validateform_annotations
description: Core annotations for aug_validateform. Pure Dart package with zero dependencies.
version: 0.0.1-dev.2
environment:
  sdk: '>=3.6.0-0 <4.0.0'

homepage: https://github.com/umarKhan1/aug_validateform
repository: https://github.com/umarKhan1/aug_validateform/tree/main/packages/aug_validateform_annotations

dependencies:
  meta: ^1.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
