name: aug_validateform
description: A zero-boilerplate, reactive validation experience using Dart Augmentations.
version: 0.0.1
environment:
  sdk: '>=3.6.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
