name: aug_validateform
description: A zero-boilerplate, type-safe validation engine for Flutter that weaves reactive logic directly into models using Dart Augmentations. Wasm-compatible and Impeller-ready.
version: 0.0.1-dev.4
environment:
  sdk: '>=3.6.0-0 <4.0.0'

homepage: https://github.com/umarKhan1/aug_validateform
repository: https://github.com/umarKhan1/aug_validateform/tree/main/packages/aug_validateform

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
